services:
  _defaults:
    autowire: true
  App\:
    resource: '../src/*'

  App\Controller\OrderController:
    public: true

  App\Listener\OrderSmsListener:
    tags: [
      {
        name: 'app.my_event_listener',
        event: order.after_insert,
        method: sendSmsToStock,
        priority: 3
      },
      {
        name: 'app.my_event_listener',
        event: order.after_insert,
        method: sendSmsToCustomer,
        priority: 2
      }
    ]

  App\Listener\OrderEmailsSubscriber:
    tags: ['app.my_event_subscriber']

  Symfony\Component\EventDispatcher\EventDispatcher:
    public:  true
