services:
  App\:
    resource: '../src/*'
    autowire: true

  App\Controller\OrderController:
    public: true
    autowire: true


  App\Listener\OrderSmsListener:
    public: true
    autowire: true

  App\Listener\OrderEmailsSubscriber:
    public: true
    autowire: true

  Symfony\Component\EventDispatcher\EventDispatcher:
    public:  true
